### ISSUE TITLE
Bar doesn't regrow when the window is expanded

### ISSUE THREAD

**Issue by StefanCov** [vaadin/vaadin-menu-bar#101] opened 2020-01-09 15:29 UTC
When the window shrinks the Menu Bar will collapse some of the menu's but when the window is expanded the menu items do not come back.

Example:
Full Screen
![image](https://user-images.githubusercontent.com/54804121/72080368-96b3db80-32f4-11ea-9e28-7259909d1598.png)

Shrunk screen
![image](https://user-images.githubusercontent.com/54804121/72080397-a7645180-32f4-11ea-8e0a-fb5bd8cc7231.png)

Resized screen
![image](https://user-images.githubusercontent.com/54804121/72080448-b945f480-32f4-11ea-90a3-cefba54d043b.png)

**Comment by web-padawan** [comment] 2020-01-21 12:00
Reproduced when buttons have `flex-grow: 1`.

**Comment by rolfsmeds** [comment] 2020-11-17 13:40
Unable to reproduce other than by overriding the menu-bar-button css with `flex-grow:1` as mentioned above.

Tweaking the component's internal css cannot be expected not to affect its functionality, so closing this issue.

(Feel free to create a separate ticket about adding a theme variant for stretching menu-bar-buttons.)

**Closed by rolfsmeds** 2020-11-17 13:40 UTC
Labels: bug
